(define (assertions)
 (assert (=>
		   (&& (equal? test_bb (=> (&& (equal? test_i10 test_arg )
									   (equal? test_i11 (length test_arg ) )
									   (equal? test_i13 (list-empty ) ) )
								   (&& test_bb14
									   ( inv0 0 0 0 (list-empty ) 0 test_arg test_arg1 ) ) ) )
			   (equal? test_bb14 (=> (&& (&& (equal? test_i15 test_i6_4 )
											 (equal? test_i16 (- (length test_arg ) 1 ) )
											 (equal? test_i17 (< test_i6_4 (- (length test_arg ) 1 ) ) ) )
										 ( inv0 test_i7_0 test_i8_1 test_i9_2 test_i5_3 test_i6_4 test_arg test_arg1 ) )
									 (&& test_bb44 test_bb43 ) ) )
			   (equal? test_bb18 (=> (&& (&& (equal? test_i19 test_arg ) (equal? test_i20 test_i6_4 ) (equal? test_i21 (list-ref-noerr test_arg test_i6_4 ) ) (equal? test_i22 test_arg1 ) (equal? test_i23 (list-ref-noerr test_arg1 0 ) ) (equal? test_i25 test_arg ) (equal? test_i26 test_i6_4 ) (equal? test_i28 (list-ref-noerr test_arg (+ test_i6_4 1 ) ) ) (equal? test_i29 test_arg1 ) (equal? test_i30 (list-ref-noerr test_arg1 1 ) ) (equal? test_i32 (* (list-ref-noerr test_arg test_i6_4 ) (list-ref-noerr test_arg1 0 ) ) ) (equal? test_i33 (* (list-ref-noerr test_arg (+ test_i6_4 1 ) ) (list-ref-noerr test_arg1 1 ) ) ) (equal? test_i35 test_i5_3 ) (equal? test_i36 (+ (* (list-ref-noerr test_arg test_i6_4 ) (list-ref-noerr test_arg1 0 ) ) (* (list-ref-noerr test_arg (+ test_i6_4 1 ) ) (list-ref-noerr test_arg1 1 ) ) ) ) (equal? test_i37 (list-append test_i5_3 (+ (* (list-ref-noerr test_arg test_i6_4 ) (list-ref-noerr test_arg1 0 ) ) (* (list-ref-noerr test_arg (+ test_i6_4 1 ) ) (list-ref-noerr test_arg1 1 ) ) ) ) ) )
										 (&& ( inv0 test_i7_0 test_i8_1 test_i9_2 test_i5_3 test_i6_4 test_arg test_arg1 )
											 (< test_i6_4 (- (length test_arg ) 1 ) ) ) )
									 test_bb38 ) )
			   (equal? test_bb38 (=> (&& (equal? test_i39 test_i6_4 ) (&& ( inv0 test_i7_0 test_i8_1 test_i9_2 test_i5_3 test_i6_4 test_arg test_arg1 )
																		  (< test_i6_4 (- (length test_arg ) 1 ) ) ) )
									 ( inv0 (* (list-ref-noerr test_arg test_i6_4 ) (list-ref-noerr test_arg1 0 ) )
											(* (list-ref-noerr test_arg (+ test_i6_4 1 ) ) (list-ref-noerr test_arg1 1 ) )
											(+ (* (list-ref-noerr test_arg test_i6_4 ) (list-ref-noerr test_arg1 0 ) ) (* (list-ref-noerr test_arg (+ test_i6_4 1 ) ) (list-ref-noerr test_arg1 1 ) ) )
											(list-append test_i5_3 (+ (* (list-ref-noerr test_arg test_i6_4 ) (list-ref-noerr test_arg1 0 ) ) (* (list-ref-noerr test_arg (+ test_i6_4 1 ) ) (list-ref-noerr test_arg1 1 ) ) ) )
											(+ test_i6_4 1 )
											test_arg
											test_arg1 ) ) )
			   (equal? test_bb41 (=> (&& (equal? test_i42 test_i5_3 )
										 (&& ( inv0 test_i7_0 test_i8_1 test_i9_2 test_i5_3 test_i6_4 test_arg test_arg1 )
											 (! (< test_i6_4 (- (length test_arg ) 1 ) ) ) ) )
									 (test test_i5_3 test_arg test_arg1) ) )
			   (equal? test_bb43 (=> (&& ( inv0 test_i7_0 test_i8_1 test_i9_2 test_i5_3 test_i6_4 test_arg test_arg1 ) (< test_i6_4 (- (length test_arg ) 1 ) ) )
									 test_bb18 ) )
			   (equal? test_bb44 (=> (&& ( inv0 test_i7_0 test_i8_1 test_i9_2 test_i5_3 test_i6_4 test_arg test_arg1 ) (! (< test_i6_4 (- (length test_arg ) 1 ) ) ) )
									 test_bb41 ) ) )
		   test_bb )))
