#!/usr/bin/env bash

# compiles benchmark and run switch converter and instruction namer on it

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"

file="$1"
ext="${file##*\.}"

clang_out=${file/.$ext/.ll}

echo "output to:" $clang_out

if [[ $file == *.c ]]
then
  clang -O0 -I"$PROJECT_ROOT/headers" -c -emit-llvm -fno-discard-value-names -S $file -o $clang_out
else
  clang++ -std=c++17 -O0 -I"$PROJECT_ROOT/headers" -c -emit-llvm -fno-discard-value-names -S $file -o $clang_out
fi

opt -load "$PROJECT_ROOT/llvm-pass/build/addEmptyBlocks/libAddEmptyBlocksPass.so" -addEmptyBlock -lowerinvoke --unreachableblockelim -instnamer -S $clang_out > tmp.ll

mv tmp.ll $clang_out

loops_out=${file/.$ext/.loops}
echo "output loops info to:" $loops_out
opt -analyze -loops $clang_out > $loops_out
